### ISSUE TITLE
Unresolved dependencies running sbt eclipse

### ISSUE THREAD

**Issue by JuanchiRios** [thin-languages/Less#1]
When i ran sbt eclipse in the repo i get warns and errors, but they are all about **sbt.ResolveException: unresolved dependency: org.uqbar#more_2.11;latest.integration: not found**
**org.uqbar#more_2.11;latest.integration: not found**. I could paste the full trace if it's necessary.

I google it and found that i should have it in "~/.ivy2/cache/org.uqbar". But there i only have identity-map,voodo and parser-test.

@GastonTS is having the same problem i have, perhaps is missing something in plugins.sbt

@nscarcella @bossiernesto any guess?

**Comment by nscarcella** [comment]
The project is build using [Uqbar's flexible dependencies](https://github.com/uqbar-project/sbt-flexible-dependencies-plugin). As long as you have more checked out on the same workspace (that is, in the same parent folder as less) you should be able to compile it fine after running sbt eclipse and cleaning the eclipse workspace.

The way it works is, if a dependency is found in the same workspace it uses it from there instead of looking it up as an Ivy or Maven dependency.

Please check if more is in the right path and also if the version present matches the dependency.

**Comment by JuanchiRios** [comment]
The problem was fixed by Renaming project "_More_" to "_more_" and updating project.sbt in less project from
`"org.uqbar" %% "more" % "latest.integration"`
to
`"org.uqbar" %% "more" % "0.0.1-SNAPSHOT"`

**Comment by JuanchiRios** [comment]
fix #1
